CREATE TABLE USER (
       ID INT NOT NULL AUTO_INCREMENT
     , NAME VARCHAR(60) NOT NULL
     , EMAIL VARCHAR(255) NOT NULL
     , HASHED_PASSWORD VARCHAR(60) NOT NULL
     , UNIQUE (EMAIL)
     , PRIMARY KEY (ID)
);

CREATE TABLE TRANSACTION (
       ID INT NOT NULL AUTO_INCREMENT
     , USER_ID INT NOT NULL
     , TRANSACTION_DATE DATE NOT NULL
     , AMOUNT DECIMAL(10, 2) NOT NULL
     , CURRENCY VARCHAR(3) NOT NULL
     , TRANSACTION_TYPE ENUM('DEBIT', 'CREDIT') NOT NULL
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_TRANSACTION FOREIGN KEY (USER_ID)
                  REFERENCES USER (ID)
);