CREATE TABLE USERS (
       ID INT  NOT NULL AUTO_INCREMENT PRIMARY KEY
     , NAME VARCHAR(60) NOT NULL UNIQUE
     , EMAIL VARCHAR(255) NOT NULL
     , ENCRYPTED_PASSWORD VARCHAR(60) NOT NULL
);

CREATE TABLE PAYMENTS (
       ID INT  NOT NULL AUTO_INCREMENT PRIMARY KEY
     , USER_ID INT NOT NULL
     , PAYMENT_DATE DATE NOT NULL
     , AMOUNT DECIMAL(10, 2) NOT NULL
     , CURRENCY VARCHAR(3) NOT NULL
     , PAYMENT_TYPE ENUM('DEBIT', 'CREDIT') NOT NULL
     , FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE FINANCIAL_INSTRUMENT (
    ID INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE USER_FINANCIAL_INSTRUMENT (
    USER_ID INT NOT NULL
    ,FINANCIAL_INSTRUMENT_ID INT NOT NULL
    ,PRIMARY KEY (USER_ID, FINANCIAL_INSTRUMENT_ID)
    ,FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
    ,FOREIGN KEY (FINANCIAL_INSTRUMENT_ID) REFERENCES FINANCIAL_INSTRUMENT(ID)
);